mysite/apps/reviewer/urls.py
from django.urls import path
from . import views

#Tambah URL Route disini
app_name = "reviewer"

urlpatterns = [
    path("", view=views.reviewer_list, name='reviewer_list'),
    path("submission", view=views.submission, name='submission'),
    path("upload", view=views.upload, name='upload'),
    path("recommend", view=views.recommend, name='recommend')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.reviewer import views

# ... your other URL patterns ...


urlpatterns = [
    path("admin/", admin.site.urls),
    # path('', views.reviewer_list, name="reviewer_list"),
    # path('add', views.add, name="add"),
    # path('edit/<int:id>', views.edit, name='edit'),
    # path('delete/<int:id>', views.delete, name='delete'),
    path("", include('apps.master.urls')),
    path("reviewer/", include('apps.reviewer.urls')),
    path("scrapping/", include('apps.scrapping.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path("editor/", include('apps.editor.urls')),
]

mysite/apps/reviewer/models.py
from django.db import models

# Create your models here.
# class Reviewer(models.Model):
#     fullname = models.CharField(max_length=100)
#     email = models.EmailField(max_length=100)
#     institution = models.CharField(max_length=100)
#     scopus_id = models.CharField(max_length=10)
#     scholar_id = models.CharField(max_length=100)
    
#     class Meta:  
#         db_table = "reviewer"

mysite/apps/reviewer/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from apps.master.models import Journal, Reviewer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import requests
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Create your views here.
def reviewer_list(request):  
    reviewers = Reviewer.objects.order_by("name").all()
    page = Paginator(reviewers, 24)
    page_number = request.GET.get("page")
    page_obj = page.get_page(page_number)
    return render(request,"reviewer/reviewer_list.html",{'page_obj':page_obj})

def add(request):
    if request.method == 'POST':
        fullname = request.POST.get('name')
        email = request.POST.get('email')
        # institution = request.POST.get('institution')
        scopus_id = request.POST.get('scopus_id')
        scholar_id = request.POST.get('scholar_id')

        reviewer = Reviewer(
            name=fullname,
            email=email,
            # institution=institution,
            scopus_id=scopus_id,
            scholar_id=scholar_id
        )

        reviewer.save()
        return redirect('reviewer:reviewer_list') 


def edit(request):
    if request.method == 'POST':
        reviewer_id = request.POST.get('reviewer_id')
        reviewer = Reviewer.objects.get(reviewer_id=reviewer_id)
        # breakpoint()
        reviewer.name = request.POST.get('name')
        reviewer.email = request.POST.get('email')
        # reviewer.institution = request.POST.get('institution')
        reviewer.scopus_id = request.POST.get('scopus_id')
        reviewer.scholar_id = request.POST.get('scholar_id')

        reviewer.save()

        return redirect('reviewer:reviewer_list')


def delete(request, id):
    employee = Reviewer.objects.get(id=id)  
    employee.delete()  
    return redirect("/") 


def submission(request):
    if request.method == "POST":
        title_input = request.POST.get("title")
        abstract_input = request.POST.get("abstract")
        
        combined_input = "{}. {}".format(title_input, abstract_input)

        # Preprocessing data input
        lowercase = combined_input.lower()
        lemmatizer = WordNetLemmatizer()
        stop_words = set(stopwords.words("english"))
        split_sentences = lowercase.split()
        input_stopwords = " ".join(
            [word for word in split_sentences if word.lower() not in stop_words]
        )
        input_tokenized = word_tokenize(input_stopwords)
        lemmatized_input = [lemmatizer.lemmatize(word) for word in input_tokenized]
        input_prepprocessed = " ".join(lemmatized_input)

        result = []
        all_journal = Journal.objects.all()
        for journal in all_journal:
            title_journal_db = journal.title
            abstract_journal_db = journal.abstrack
            doi_journal = journal.other
            author_journal_db = journal.reviewer.all().values()
            combined_journal_db = "{}. {}".format(title_journal_db, abstract_journal_db)

            # Preprocessing data db
            lowercase_journal_db = combined_journal_db.lower()
            lemmatizer = WordNetLemmatizer()
            split_sentences_journal_db = lowercase_journal_db.split()

            data_journal_db_stopwords = " ".join(
                [
                    word
                    for word in split_sentences_journal_db
                    if word.lower() not in stop_words
                ]
            )
            data_journal_db_tokenized = word_tokenize(data_journal_db_stopwords)
            lemmatized_data_journal_db = [
                lemmatizer.lemmatize(word) for word in data_journal_db_tokenized
            ]
            data_journal_db_preprocessed = " ".join(lemmatized_data_journal_db)

            # TF-IDF
            vectorizer = TfidfVectorizer()
            tfidf_matrix = vectorizer.fit_transform(
                [input_prepprocessed, data_journal_db_preprocessed]
            )

            # Count similarity
            similarity_matrix = cosine_similarity(tfidf_matrix, tfidf_matrix)
            similarity = (similarity_matrix[0][1]) * 100
            int_similarity = int(similarity)
            round_similarity = round(similarity, 2)

            result.append(
                {
                    "title_db": title_journal_db,
                    "abstract_db": abstract_journal_db,
                    "doi_journal" : doi_journal,
                    "author_db": author_journal_db[0],
                    "similarity_mentah": similarity,
                    "similarity_bulat": int_similarity,
                    "similarity_koma": round_similarity,
                }
            )
        sorted_result = sorted(
            result, key=lambda x: x["similarity_mentah"], reverse=True
        )

        top_ten_result = sorted_result[:10]
        grouped_author = {}

        for journal in top_ten_result:
            author = journal["author_db"]
            author_name = author["name"]
            if author_name not in grouped_author:
                grouped_author[author_name] = [journal]
            else:
                grouped_author[author_name].append(journal)
        # breakpoint()
        return render(
            request,
            "reviewer/recommended_reviewers.html",
            {
                "title_input": title_input,
                "abstract_input": abstract_input,
                "result": grouped_author,
            },
        )
    return render(request, "reviewer/journal-submission.html")


def upload(request):
    return render(request, "reviewer/file_uploader.html")

def recommend(request):
    return render(request, "reviewer/recommended_reviewers.html")

mysite/templates/reviewer/index.html
{% load static %} {% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Airlangga Journal Database Reviewer</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@200;300;400;500;600;700;800&family=EB+Garamond:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
    {% tailwind_preload_css %} {% tailwind_css %}
</head>
<body class="container mx-auto flex items-center justify-center">
    <form action="{% url "reviewer:recommend" %}" method="post">
        {% csrf_token %}
        {{ form }}
        <div class="flex mt-36 shadow-lg rounded-2xl">
            <div class="border-2 p-9 rounded-tl-2xl rounded-bl-2xl">
                <h1 class="text-2xl font-bold">
                    Journal Submission Form
                </h1>
                <div class="flex flex-col gap-4 py-4">
                    <div>
                        <h2>
                            Journal Title
                        </h2>
                        <input type="text" id="title" name="title" class="w-[408px] shadow-md border-opacity-30 border-[1px] border-black" placeholder="Lorem Ipsum dolor sit amet...">
                    </div>
                    <div>
                        <h2>
                            Publish Date
                        </h2>
                        <input type="date" id="date" name="date" class="w-[216px] shadow-md border-opacity-30 border-[1px] border-black">
                    </div>
                    <div>
                        <h2>
                            Abstract
                        </h2>
                        <textarea type="text" id="abstract"  rows="5" name="abstract" class="w-[408px] shadow-md border-opacity-30 border-[1px] border-black" placeholder="Lorem Ipsum Dolor sit amet..."></textarea>
                    </div>
                    <div class="save-button">
                        <button type="submit" class="third-btn">
                            <div class="border-black border-[1px] px-6 rounded-lg py-1">Save and Continue</div>
                        </button>
                    </div>
                </div>
            </div>
            <div class="rounded-tr-2xl rounded-br-2xl flex select-none">
                <img src="{% static 'reviewer/images/submission.png' %}" alt="placeholder">
            </div>
        </div> 
    </form>
    <div class="absolute top-12 right-12 w-12">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-log-out"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" x2="9" y1="12" y2="12"/></svg>
    </div>
</body>
</html>

mysite/templates/reviewer/journal-submission.html
{% load static %} {% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Airlangga Journal Database Reviewer</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Dosis:wght@200;300;400;500;600;700;800&family=EB+Garamond:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500;1,600;1,700;1,800&display=swap"
      rel="stylesheet"
    />
    {% tailwind_preload_css %} {% tailwind_css %}
  </head>
  <body class="container mx-auto flex items-center justify-center">
    <form action="" method="post">
      {% csrf_token %} {{ form }}
      <div class="flex mt-36 shadow-lg rounded-2xl">
        <div class="border-2 p-9 rounded-tl-2xl rounded-bl-2xl">
          <h1 class="text-2xl font-bold">Journal Submission Form</h1>
          <div class="flex flex-col gap-4 py-4">
            <div>
              <h2>Journal Title</h2>
              <input
                type="text"
                id="title"
                name="title"
                class="w-[408px] shadow-md border-opacity-30 border-[1px] border-black"
                placeholder="Lorem Ipsum dolor sit amet..."
                required
              />
            </div>
            <div>
              <h2>Abstract</h2>
              <textarea
                type="text"
                id="abstract"
                rows="5"
                name="abstract"
                class="w-[408px] shadow-md border-opacity-30 border-[1px] border-black"
                placeholder="Lorem Ipsum Dolor sit amet..."
                required
              ></textarea>
            </div>
            <div class="save-button">
              <button type="submit" class="third-btn">
                <div class="border-black border-[1px] px-6 rounded-lg py-1">
                  Save and Continue
                </div>
              </button>
            </div>
            <div class="mt-0.5">
              <a class="border-black border-[1px] px-6 rounded-lg py-1" href="{% url "dashboard" %}">Back</a>
            </div>
          </div>
        </div>
        <div class="rounded-tr-2xl rounded-br-2xl flex select-none">
          <img
            src="{% static 'reviewer/images/submission.png' %}"
            alt="placeholder"
          />
        </div>
      </div>
    </form>
  </body>
</html>

mysite/templates/reviewer/recommended_reviewers.html
{% load static %} {% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Airlangga Journal Database Reviewer</title>
    <link
      rel="stylesheet"
      href="{% static 'reviewer/style/floren-style.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Dosis:wght@200;300;400;500;600;700;800&family=EB+Garamond:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500;1,600;1,700;1,800&display=swap"
      rel="stylesheet" />
    <script
      type="module"
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    {% tailwind_preload_css %} {% tailwind_css %}
  </head>
  <body>
    <div class="recommended-reviewers-page">
      <div class="recommended-reviewers-container">
        <!-- BAGIAN ATAS (LIST REVIEWER) LEFT COLUMN-->
        <div class="">
          <div class="left-column-1">
            <h1>Who do you want to review your paper?</h1>
            <br />
            <!--PLACEHOLDER REVIEWER SELECTION-->
            {%for data, values in result.items %}
            <div class="flex flex-col border border-black rounded-md w-full">
              <div class="flex justify-between">
                <div
                  class="flex p-4 flex-col w-full justify-center"
                  id="reviewer-card">
                  <div class="flex justify-between items-center">
                    <div class="flex items-center">
                      <img
                        src="{% static 'reviewer/images/Vector.png' %}"
                        alt="placeholder"
                        class="mr-3" />
                      <p class="text-xl font-bold">{{data}}</p>
                    </div>
                    <div class="">
                      <p class="text-xl">{{ values.0.author_db.email }}</p>
                    </div>
                  </div>
                  <!--Penelitian Sebelumnya (Deafult:hidden)-->
                  <div class="journal hidden">
                    <div class="flex flex-col">
                      <p class="text-xl mt-4 mb-3">Research Papers</p>
                      {% for value in values %}
                      <div class="flex justify-between items-center mb-3">
                        <div class="">
                          <a
                            href="https://doi.org/{{ value.doi_journal }}"
                            target="_blank">
                            <p class="">{{value.title_db}}</p>
                          </a>
                        </div>
                        <div class="">
                          <p class="">{{value.similarity_koma}}%</p>
                        </div>
                      </div>
                      {% endfor %}
                    </div>
                  </div>
                  <div class="flex items-center justify-center">
                    <button id="showDataBtn" class="cursor-pointer">
                      <ion-icon name="chevron-down-outline"></ion-icon>
                    </button>
                    <button id="hideDataBtn" class="cursor-pointer hidden">
                      <ion-icon name="chevron-up-outline"></ion-icon>
                    </button>
                  </div>
                </div>
                <div
                  class="flex p-3 justify-center items-center bg-black rounded-br-md rounded-tr-md">
                  <p class="text-white text-2xl">Choose</p>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>

        <!-- BAGIAN BAWAH BACK SAMA SAVE-->
        <div class="recrev-container-3">
          <div class="back-button">
            <button type="button" class="third-btn">
              <a href="" style="color: black; text-decoration: none">Back</a>
            </button>
          </div>

          <div class="save-button">
            <button type="button" class="third-btn">
              <a href="" style="color: black; text-decoration: none">
                Save and Continue
              </a>
            </button>
          </div>
        </div>
      </div>
    </div>
    <script>
      const cards = document.querySelectorAll("#reviewer-card");

      cards.forEach((ele) => {
        const show = ele.querySelector("#showDataBtn");
        const journal = ele.querySelector(".journal");
        const hidden = ele.querySelector("#hideDataBtn");
        show.addEventListener("click", function () {
          journal.classList.remove("hidden");
          show.classList.add("hidden");
          hidden.classList.remove("hidden");
        });

        hidden.addEventListener("click", function () {
          journal.classList.add("hidden");
          show.classList.remove("hidden");
          hidden.classList.add("hidden");
        });
      });
    </script>
  </body>
</html>

mysite/templates/reviewer/upload data OJS.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'reviewer/style/upload-data-styles.css' %}"> <!-- Menghubungkan file CSS -->
    <title>Upload Data OJS</title>
</head>
<body>
    {% if messages %}
        <div class="messages" style="position: absolute; top: 0; left: 0; margin: 36px 0px 0px 36px;">
            {% for message in messages %}
                {% if message.tags == 'success' %}
                <div class="success" style="border: 1px solid black; border-radius: 16px; background-color: rgb(232, 255, 234,1); padding: 5px 20px 10px 20px;">
                    <button class="close-button" style="position: absolute; top: 0px; right: 0px; background-color: transparent; border: none; cursor: pointer; margin: 0; padding-right: 15px;" onclick="closeMessage(this)">X</button>
                    <h3 style="text-align: left;">Upload Success</h3>
                    <p>{{ message }}</p>
                </div>
                {% elif message.tags == 'info' %}
                <div class="info" style="border: 1px solid black; border-radius: 16px; background-color: rgb(255, 255, 232); padding: 5px 20px 10px 20px;">
                    <button class="close-button" style="position: absolute; top: 0px; right: 0px; background-color: transparent; border: none; cursor: pointer; margin: 0; padding-right: 15px;" onclick="closeMessage(this)">X</button>
                    <h3 style="text-align: left;">Upload Failed</h3>
                    <p>{{ message }}</p>
                </div>
                {% else %}
                <div class="error" style="border: 1px solid black; border-radius: 16px; background-color: rgba(255, 232, 232, 1); padding: 5px 20px 10px 20px;">
                    <button class="close-button" style="position: absolute; top: 0; right: 0px; background-color: transparent; border: none; cursor: pointer; margin: 0; padding-right: 15px;" onclick="closeMessage(this)">X</button>
                    <h3 style="text-align: left;">Upload Error</h3>
                    <p>{{ message }}</p>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
    
    <div class="container">
        <h1>Upload OJS Data</h1>
        <form method="post" enctype="multipart/form-data">
            <div class="nested-container">
                {% csrf_token %}
                <input type="file" id="myFile" style="display:none" name="excel_file">
                {% load static %}
                <img src="{% static 'reviewer/images/ojss.png' %}" onclick="document.getElementById('myFile').click();" alt="Click to select a file" width="120" height="150">
                <span id="file-name" style="display: none; margin-top: 30px;"></span>
                <p id="text-gone" class="image-description">Upload OJS Data Here</p>
            </div>
            <a href="{% url "dashboard" %}">
                <button type="button" id="back-button">Back</button>
            </a>
            <input type="submit" style="padding: 5px 12px 5px 12px;" value="Save and Continue"></input>
        </form>
    </div>
    
</body>

<script>
    function closeMessage(button) {
        var message = button.parentNode; 
        message.style.display = "none";
    }

    document.getElementById('myFile').addEventListener('change', function() {
        var fileName = this.value.split('\\').pop(); 
        var fileSpan = document.getElementById('file-name');
        fileSpan.textContent = 'Selected file: ' + fileName;
        fileSpan.style.display = 'inline-block'; 
        var textGone = document.getElementById('text-gone');
        textGone.style.display = 'none';
    });
</script>

</html>