mysite/apps/editor/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("dashboard", views.dashboard, name="dashboard"),
]

mysite/apps/reviewer/urls.py
from django.urls import path
from . import views

#Tambah URL Route disini
app_name = "reviewer"

urlpatterns = [
    path("", view=views.reviewer_list, name='reviewer_list'),
    path("submission", view=views.submission, name='submission'),
    path("upload", view=views.upload, name='upload'),
    path("recommend", view=views.recommend, name='recommend')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.reviewer import views

# ... your other URL patterns ...


urlpatterns = [
    path("admin/", admin.site.urls),
    # path('', views.reviewer_list, name="reviewer_list"),
    # path('add', views.add, name="add"),
    # path('edit/<int:id>', views.edit, name='edit'),
    # path('delete/<int:id>', views.delete, name='delete'),
    path("", include('apps.master.urls')),
    path("reviewer/", include('apps.reviewer.urls')),
    path("scrapping/", include('apps.scrapping.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path("editor/", include('apps.editor.urls')),
]

mysite/apps/editor/models.py
from django.db import models

# Create your models here.

mysite/apps/editor/views.py
from django.shortcuts import render
from apps.master.models import Scrapping, Upload_Data
from apps.reviewer.views import upload

# Create your views here.
def dashboard(request):
  try:
    reviewer_scrap_date = Scrapping.objects.filter(isReviewerScrap = True).latest('scrapping_date')
    journal_scrap_date = Scrapping.objects.filter(isReviewerScrap = False).latest('scrapping_date')
    upload_data_date = Upload_Data.objects.latest("upload_date")
    context = {"reviewer" : reviewer_scrap_date, "journal" : journal_scrap_date, "upload" : upload_data_date}
  except:
    context = {"reviewer" : None, "journal" : None, "upload" : None}
    
  return render(request, 'editor/dashboard.html', context)

mysite/templates/editor/dashboard.html
{% load static %} {% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <title>Editor Dashboard - Airlangga Journal Database Reviewer</title>
    {% tailwind_preload_css %} {% tailwind_css %}
  </head>
  <body>
    <!-- Header -->
    {% if messages %}
    <div class="messages" style="position: absolute; top: 0; left: 0; margin: 36px 0px 0px 36px;">
        {% for message in messages %}
            {% if message.tags == 'success' %}
            <div class="success" style="border: 1px solid black; border-radius: 16px; background-color: rgb(232, 255, 234,1); padding: 5px 20px 10px 20px;">
                <button class="close-button" style="position: absolute; top: 0px; right: 0px; background-color: transparent; border: none; cursor: pointer; margin: 0; padding-right: 15px;" onclick="closeMessage(this)">X</button>
                <h3 style="text-align: left;">Upload Success</h3>
                <p>{{ message }}</p>
            </div>
            {% elif message.tags == 'info' %}
            <div class="info" style="border: 1px solid black; border-radius: 16px; background-color: rgb(255, 255, 232); padding: 5px 20px 10px 20px;">
                <button class="close-button" style="position: absolute; top: 0px; right: 0px; background-color: transparent; border: none; cursor: pointer; margin: 0; padding-right: 15px;" onclick="closeMessage(this)">X</button>
                <h3 style="text-align: left;">Upload Failed</h3>
                <p>{{ message }}</p>
            </div>
            {% else %}
            <div class="error" style="border: 1px solid black; border-radius: 16px; background-color: rgba(255, 232, 232, 1); padding: 5px 20px 10px 20px;">
                <button class="close-button" style="position: absolute; top: 0; right: 0px; background-color: transparent; border: none; cursor: pointer; margin: 0; padding-right: 15px;" onclick="closeMessage(this)">X</button>
                <h3 style="text-align: left;">Upload Error</h3>
                <p>{{ message }}</p>
            </div>
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}
    <header
      class="text-6xl container mx-auto text-center mt-28 mb-16 font-serif"
    >
      Editor Dashboard
    </header>

    <!-- Content -->
    <section class="container flex justify-evenly mx-auto">
      <!-- OJS Data -->
      {{ message }}
      <div
        class="w-[390px] shadow-lg border-[1px] rounded-3xl text-center py-10"
      >
        <header class="text-5xl">OJS Data</header>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="1"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="mx-auto w-96"
        >
          <rect
            width="18"
            height="18"
            x="3"
            y="3"
            rx="2"
            ry="2"
          />
          <line
            x1="3"
            x2="21"
            y1="9"
            y2="9"
          />
          <line
            x1="3"
            x2="21"
            y1="15"
            y2="15"
          />
          <line
            x1="9"
            x2="9"
            y1="9"
            y2="21"
          />
          <line
            x1="15"
            x2="15"
            y1="9"
            y2="21"
          />
        </svg>
        <div class="w-72 mx-auto mb-5 -mt-5">
          {% if upload.upload_date is None  %}
            <p class="text-left">Last Synced: {{ "Data has never been updated" }}</p>
            {% else %}
            <p class="text-left">Last Synced: {{ upload.upload_date|date:"d/m/Y" }}</p>
          {% endif %}
        </div>
        <div class="flex justify-between w-72 mx-auto">
          <a href="{% url "reviewer:reviewer_list" %}">
            <div class="w-32 border-2 py-1 rounded-lg border-black">
              View Data
            </div>
          </a>
          <a href="{% url "upload data OJS" %}">
            <div class="w-32 border-2 py-1 rounded-lg border-black">
              Update Now
            </div>
          </a>
        </div>
      </div>

      <!-- Reviewers -->
      <div
        class="w-[390px] shadow-lg border-[1px] rounded-3xl text-center py-10"
      >
        <!-- Card title -->
        <header class="text-5xl mb-8">Reviewers</header>
        <!-- Content -->
        <div class="flex flex-col items-center gap-4 mb-11">
          <!-- Reviewer Cards -->
          <div
            class="flex px-4 py-6 border-2 border-slate-500 shadow-lg rounded-lg justify-center w-fit gap-2"
          >
            <!-- Reviewer profile -->
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="w-12"
            >
              <path d="M18 21a6 6 0 0 0-12 0" />
              <circle
                cx="12"
                cy="11"
                r="4"
              />
              <rect
                width="18"
                height="18"
                x="3"
                y="3"
                rx="2"
              />
            </svg>
            <div class="text-left">
              <p class="font-bold">Dr. Sandra Algorithmson</p>
              <p>Data Science Institute</p>
            </div>
          </div>
          <!-- Reviewer Cards -->
          <div
            class="flex px-4 py-6 border-2 border-slate-500 shadow-lg rounded-lg justify-center w-fit gap-2"
          >
            <!-- Reviewer profile -->
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="w-12"
            >
              <path d="M18 21a6 6 0 0 0-12 0" />
              <circle
                cx="12"
                cy="11"
                r="4"
              />
              <rect
                width="18"
                height="18"
                x="3"
                y="3"
                rx="2"
              />
            </svg>
            <div class="text-left">
              <p class="font-bold">Dr. Sandra Algorithmson</p>
              <p>Data Science Institute</p>
            </div>
          </div>
          <!-- Reviewer Cards -->
          <div
            class="flex px-4 py-6 border-2 border-slate-500 shadow-lg rounded-lg justify-center w-fit gap-2"
          >
            <!-- Reviewer profile -->
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="w-12"
            >
              <path d="M18 21a6 6 0 0 0-12 0" />
              <circle
                cx="12"
                cy="11"
                r="4"
              />
              <rect
                width="18"
                height="18"
                x="3"
                y="3"
                rx="2"
              />
            </svg>
            <div class="text-left">
              <p class="font-bold">Dr. Sandra Algorithmson</p>
              <p>Data Science Institute</p>
            </div>
          </div>
        </div>
        <div class="flex justify-center w-72 mx-auto">
          <a href="{% url "reviewer:submission" %}">
            <div class="w-32 border-2 py-1 rounded-lg border-black">
              Recommend
            </div>
          </a>
        </div>
      </div>

      <!-- Scraping n Crawling -->
      <div class="flex flex-col justify-between">
        <!-- Reviewer Scraping -->
        <div
          class="w-[390px] shadow-lg border-[1px] rounded-3xl text-center px-8 py-20"
        >
          <header class="text-4xl mb-8">Reviewer Scraping</header>
          <div class="flex justify-between items-center px-8">
            {% if reviewer.scrapping_date is None  %}
              <p class="text-left">Last Synced: {{ "Data has never been updated" }}</p>
            {% else %}
              <p class="text-left">Last Synced: {{ reviewer.scrapping_date|date:"d/m/Y" }}</p>
            {% endif %}
            <form action="{% url "reviewer_scrapping" %}">
              <button type="submit">
                <div class="border-2 px-4 py-0.5 rounded-lg border-black">Go</div>
              </button>
            </form>
          </div>
        </div>
        <!-- Journal Scraping -->
        <div
          class="w-[390px] shadow-lg border-[1px] rounded-3xl text-center px-8 py-20"
        >
          <header class="text-4xl mb-8">Journal Scraping</header>
          <div class="flex justify-between items-center px-8">
            {% if journal.scrapping_date is None  %}
              <p class="text-left">Last Synced: {{ "Data has never been updated" }}</p>
            {% else %}
              <p class="text-left">Last Synced: {{ journal.scrapping_date|date:"d/m/Y" }}</p>
            {% endif %}
            <form action="{% url 'journal_scrapping' %}">
              <button type="submit">
                <div class="border-2 px-4 py-0.5 rounded-lg border-black">Go</div>
              </button>
            </form>
          </div>
        </div>
        <!-- Web Crawling -->
      </div>
    </section>

    <!-- Logout Button -->
    <form id="logout-form" action="{% url "logout" %}" method="post">
      {% csrf_token %}
      <div class="absolute top-12 right-12 cursor-pointer" onclick="logout()">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="1"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="lucide lucide-log-out w-14"
        >
          <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
          <polyline points="16 17 21 12 16 7" />
          <line
            x1="21"
            x2="9"
            y1="12"
            y2="12"
          />
        </svg>
      </div>
    </form>
  </body>
<script>
  function logout(){
    const logoutForm = document.getElementById("logout-form")
    logoutForm.submit()
  }

  function closeMessage(button) {
    var message = button.parentNode; 
    message.style.display = "none";
  }
</script>
</html>